name: quiz
description: quiz app.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/picture.png
   - assets/face.jpg
   - assets/google.png
